# Generated by Django 5.1.4 on 2025-01-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.IntegerField(default=800),
        ),
    ]
