# Generated by Django 5.1.4 on 2025-01-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_service_clientquote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientquote',
            name='name',
        ),
        migrations.AddField(
            model_name='clientquote',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clientquote',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
