# Generated by Django 5.1.4 on 2025-01-09 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_clientquote_name_clientquote_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientquote',
            old_name='service_type',
            new_name='services',
        ),
    ]
