name: Sync Backend Directory to Backend Branch for Deployment

on:
  push:
    branches:
      - main

jobs:
  sync-backend:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the main branch
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Set up Git
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      # Step 3: Create or switch to the backend branch
      - name: Switch to Backend Branch
        run: |
          git fetch origin
          if git show-ref --quiet refs/heads/backend; then
            git checkout backend
          else
            git checkout -b backend
          fi

      # Step 4: Clear the backend branch
      - name: Clear Backend Branch
        run: |
          git rm -r --cached --ignore-unmatch * || echo "No files to remove"
          git clean -fd || echo "Nothing to clean"

      # Step 5: Copy contents of backend directory to the root
      - name: Move Backend Directory to Root
        run: |
          git checkout main -- backend/
          # First move all contents to root
          cp -r backend/* .
          # Only remove the top-level backend directory, preserving any nested ones
          find . -maxdepth 1 -type d -name "backend" -exec rm -rf {} +
          git add .
          git commit -m "Sync backend directory to backend branch" || echo "No changes to commit"

      # Step 6: Push changes to backend branch
      - name: Push Changes
        run: |
          git push origin backend --force
